### ISSUE TITLE
Env vars don't seem to be able to be set from scratch

### ISSUE THREAD

**Issue by erithmetic** [faradayio/credentials_to_env#1]
I have a Secretfile:

```
FOO bar/baz:bat
QUUX qat/doq
```

I then run

```
# credentials-to-env env
Error: can't access secure credential FOO: environment variable not found
# export FOO=foo
# credentials-to-env env
Error: can't access secure credential QUUX: environment variable not found
```

Which means things are OK if environment variables are preset?

**Comment by emk** [comment]
Normally env values take precedence over vault, but there's a flag to
handle special cases, like when a Dockerfile provides a bogus ENV value
that you can't fix and you want to pull values from vault instead.

If you can find a use case that it doesn't handle, let me know. But check
--help for flags first.

Le 30 août 2016 6:08 PM, "Derek Kastner" notifications@github.com a
écrit :

**Comment by erithmetic** [comment]
I think this was actually a case of missing `VAULT_ENV` or `VAULT_*`
